import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css';
import stylesCommon from '@/styles/Common.module.css';
import { useUser } from '@auth0/nextjs-auth0/client';
import VehicleForm from '../components/VehicleForm';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Cookies from 'js-cookie';


export default function Home() {
    const [token, setToken] = useState<string | null>(null);
    const router = useRouter();
    const getAuthorizationCode = () => {
        const url = new URL('https://dev-jmdtw3b5y1usoxa1.eu.auth0.com/authorize');
        url.searchParams.append('response_type', 'code');
        url.searchParams.append('client_id', 'upxBUXTPTeTxvCOzgvV9jM9qvBYC63lH');
        url.searchParams.append('redirect_uri', 'http://localhost:3000/api/callback');
        url.searchParams.append('scope', 'openid profile email');
        url.searchParams.append('audience', 'https://localhost/carmaintenance');
        router.push(url.toString());
    };

    /*testing if cookie is recieved from callback.ts*/
    useEffect(() => {
        const accessToken = Cookies.get('token') || null;
        console.log('Token retrieved from cookie:', accessToken);
        setToken(accessToken);
    }, [router.asPath]);

    const logout = () => {
        Cookies.remove('token');

        /*This can be done in a better way*/
        window.location.href = '/';
    };




    function renderLoginPage() {
        return (
            <>
            <div className={styles.container}>
                <p>Experience the future of automotive care</p>

                <div className={styles.listContainer}>
                    <p>Effortlessly</p>
                    <ul>
                        <li>log services</li>
                        <li>track cost</li>
                        <li>stay ahead with a personalized <br></br>maintenance schedule</li>
                    </ul>
                </div>
            </div>

            <div className={styles.backgroundImage}>



                    <button className={styles.login_btn} onClick={() => getAuthorizationCode()}>
                        Login
                    </button>

                    <button className={styles.login_btn} onClick={() => getAuthorizationCode()}>
                        Get Started Now
                    </button>
            </div>
            </>
        )
    }

    function renderDashboard() {
        if (!token) {
            return <p>Loading...</p>;
        }

        console.log("Below is the token");
        console.log(token);
        console.log("Testing console log");
        return (
            <>
                <div className={styles.user_info_container}>
                    <div className={styles.user_info}>
                        <p>name</p>
                    </div>


                    <button className={styles.logout_btn} onClick={logout}>Logout</button>
                </div>
                <h2 className={styles.AddCarText}>Add you car</h2>
                <div className={styles.AddCarContainer}>
                    
                    <div className={styles.infoContainer}>
                        <p>To provide you with accurate service recommendations and maintenance updates tailored to your vehicle, please enter your car&apos;s details. </p>
                        <p>Let&apos;s get started!!</p>
                    </div>

                    <VehicleForm token={token} />
                </div>
             </>
        );
    }



  return (
    <>
      <Head>
        <title>AutoCare+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <main className={styles.main}>
              <h1 className={token ? stylesCommon.loggedIn : stylesCommon.loggedOut}>
                  {token ? 'AutoCare+' : 'Discover AutoCare+'}
              </h1>

              {!token && renderLoginPage()}

              {token && renderDashboard()}

              {token && (
                  <button onClick={logout}>Logout</button>
              )}
          </main>
    </>
  )
}
